// FaithTrack/frontend-react/src/components/ResourceForm.jsx
import React, { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import resourceService from '../services/resourceService';

function ResourceForm({ resourceId }) {
  const {
    register,
    handleSubmit,
    setValue,
    formState: { errors },
  } = useForm();

  const navigate = useNavigate();
  const isEditMode = !!resourceId;

  const onSubmit = async (data) => {
    try {
      if (isEditMode) {
        await resourceService.updateResource(resourceId, data);
      } else {
        await resourceService.createResource(data);
      }
      navigate('/resources');
    } catch (err) {
      console.error('Save error:', err);
    }
  };

  useEffect(() => {
    if (isEditMode) {
      resourceService.getResourceById(resourceId).then((res) => {
        const fields = ['title', 'description', 'category_id', 'scripture'];
        fields.forEach((field) => setValue(field, res[field]));
      });
    }
  }, [resourceId, setValue, isEditMode]);

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      {/* Title */}
      <div className="mb-3">
        <label className="form-label">Title</label>
        <input
          className={`form-control ${errors.title ? 'is-invalid' : ''}`}
          {...register('title', { required: true, minLength: 3 })}
        />
        {errors.title && (
          <div className="invalid-feedback">
            Title is required and must be at least 3 characters.
          </div>
        )}
      </div>

      {/* Description */}
      <div className="mb-3">
        <label className="form-label">Description</label>
        <textarea
          className={`form-control ${errors.description ? 'is-invalid' : ''}`}
          {...register('description', { required: true, minLength: 10 })}
        />
        {errors.description && (
          <div className="invalid-feedback">
            Description must be at least 10 characters.
          </div>
        )}
      </div>

      {/* Category ID */}
      <div className="mb-3">
        <label className="form-label">Category ID</label>
        <input
          type="number"
          className={`form-control ${errors.category_id ? 'is-invalid' : ''}`}
          {...register('category_id', { required: true, min: 1 })}
        />
        {errors.category_id && (
          <div className="invalid-feedback">
            Category ID is required and must be at least 1.
          </div>
        )}
      </div>

      {/* Scripture */}
      <div className="mb-3">
        <label className="form-label">Scripture</label>
        <input
          className={`form-control ${errors.scripture ? 'is-invalid' : ''}`}
          {...register('scripture', { required: true })}
        />
        {errors.scripture && (
          <div className="invalid-feedback">Scripture is required.</div>
        )}
      </div>

      <button type="submit" className="btn btn-success">
        {isEditMode ? 'Update' : 'Create'}
      </button>
      <button
        type="button"
        className="btn btn-secondary ms-2"
        onClick={() => navigate('/resources')}
      >
        Cancel
      </button>
    </form>
  );
}

export default ResourceForm;

// FaithTrack/frontend/src/app/components/resource-form/resource-form.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ResourceService } from '../../../app/services/resource.service';
import { ReactiveFormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';

@Component({
  standalone: true,
  selector: 'app-resource-form',
  templateUrl: './resource-form.component.html',
  styleUrls: ['./resource-form.component.scss'],
  imports: [ReactiveFormsModule, CommonModule]
})
export class ResourceFormComponent implements OnInit {
  resourceForm!: FormGroup;
  isEditMode = false;
  resourceId?: number;

  constructor(
    private fb: FormBuilder,
    private route: ActivatedRoute,
    private router: Router,
    private resourceService: ResourceService
  ) {}

  ngOnInit(): void {
    this.resourceForm = this.fb.group({
      title: ['', [Validators.required, Validators.minLength(3)]],
      description: ['', [Validators.required, Validators.minLength(10)]],
      category_id: [null, [Validators.required, Validators.min(1)]],
      scripture: ['', [Validators.required]]
    });

    this.route.paramMap.subscribe(params => {
      const id = params.get('id');
      if (id) {
        this.isEditMode = true;
        this.resourceId = +id;
        this.loadResource(this.resourceId);
      }
    });
  }

  loadResource(id: number): void {
    this.resourceService.getResourceById(id).subscribe({
      next: (data) => this.resourceForm.patchValue(data),
      error: (err) => console.error('Error loading resource:', err)
    });
  }

  onSubmit(): void {
    if (this.resourceForm.invalid) {
      this.resourceForm.markAllAsTouched();
      return;
    }

    const formData = this.resourceForm.value;

    if (this.isEditMode && this.resourceId) {
      this.resourceService.updateResource(this.resourceId, formData).subscribe(() => {
        this.router.navigate(['/resources']);
      });
    } else {
      this.resourceService.createResource(formData).subscribe(() => {
        this.router.navigate(['/resources']);
      });
    }
  }

  onCancel(): void {
    this.router.navigate(['/resources']);
  }

  // Handy getter to clean up template
  get f() {
    return this.resourceForm.controls;
  }
}

<div class="container mt-4">
  <h2 class="mb-3">{{ isEditMode ? 'Edit Resource' : 'Add New Resource' }}</h2>

  <form [formGroup]="resourceForm" (ngSubmit)="onSubmit()">

    <!-- Title -->
    <div class="mb-3">
      <label class="form-label">Title</label>
      <input
        type="text"
        class="form-control"
        formControlName="title"
        [class.is-invalid]="f['title'].touched && f['title'].invalid"
      />
      <div class="invalid-feedback" *ngIf="f['title'].touched && f['title'].errors">
        <div *ngIf="f['title'].errors['required']">Title is required.</div>
        <div *ngIf="f['title'].errors['minlength']">Title must be at least 3 characters.</div>
      </div>
    </div>

    <!-- Description -->
    <div class="mb-3">
      <label class="form-label">Description</label>
      <textarea
        class="form-control"
        formControlName="description"
        [class.is-invalid]="f['description'].touched && f['description'].invalid"
      ></textarea>
      <div class="invalid-feedback" *ngIf="f['description'].touched && f['description'].errors">
        <div *ngIf="f['description'].errors['required']">Description is required.</div>
        <div *ngIf="f['description'].errors['minlength']">Minimum 10 characters required.</div>
      </div>
    </div>

    <!-- Category ID -->
    <div class="mb-3">
      <label class="form-label">Category ID</label>
      <input
        type="number"
        class="form-control"
        formControlName="category_id"
        [class.is-invalid]="f['category_id'].touched && f['category_id'].invalid"
      />
      <div class="invalid-feedback" *ngIf="f['category_id'].touched && f['category_id'].errors">
        <div *ngIf="f['category_id'].errors['required']">Category ID is required.</div>
        <div *ngIf="f['category_id'].errors['min']">Must be at least 1.</div>
      </div>
    </div>

    <!-- Scripture -->
    <div class="mb-3">
      <label class="form-label">Scripture</label>
      <input
        type="text"
        class="form-control"
        formControlName="scripture"
        [class.is-invalid]="f['scripture'].touched && f['scripture'].invalid"
      />
      <div class="invalid-feedback" *ngIf="f['scripture'].touched && f['scripture'].errors">
        <div *ngIf="f['scripture'].errors['required']">Scripture is required.</div>
      </div>
    </div>

    <!-- Submit -->
    <button type="submit" class="btn btn-success">
      {{ isEditMode ? 'Update' : 'Create' }}
    </button>
    <button type="button" class="btn btn-secondary ms-2" (click)="onCancel()">Cancel</button>
  </form>
</div>
