// FaithTrack/frontend/src/app/components/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-navbar',
  standalone: true, //
  imports: [RouterModule, CommonModule], //
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss'],
})
export class NavbarComponent {}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark px-4">
  <a class="navbar-brand fw-bold me-4" routerLink="/">FaithTrack</a>

  <div class="collapse navbar-collapse">
    <ul class="navbar-nav ms-auto">
      <li class="nav-item">
        <a class="nav-link" routerLink="/resources" routerLinkActive="active">All Resources</a>
      </li>
      <li class="nav-item ms-3">
        <a class="nav-link" routerLink="/resources/create" routerLinkActive="active">Add Resource</a>
      </li>
    </ul>
  </div>
</nav>

// FaithTrack/frontend-react/src/components/Navbar.jsx
import React from 'react';
import { Link } from 'react-router-dom';

function Navbar() {
  return (
    <nav className="navbar navbar-dark bg-dark px-4">
      <Link to="/" className="navbar-brand">FaithTrack</Link>
      <div>
        <Link to="/resources" className="nav-link d-inline text-white">All Resources</Link>
        <Link to="/resources/new" className="nav-link d-inline text-white ms-3">Add Resource</Link>
      </div>
    </nav>
  );
}

export default Navbar;
