// FaithTrack/frontend/src/app/components/resource-list/resource-list.component.ts
import { Component, OnInit } from '@angular/core';
import { RouterModule, Router } from '@angular/router';
import { CommonModule } from '@angular/common'; // ✅ Needed for *ngFor
import { ResourceService, Resource } from '../../../app/services/resource.service';

@Component({
  selector: 'app-resource-list',
  standalone: true,
  templateUrl: './resource-list.component.html',
  styleUrls: ['./resource-list.component.scss'],
  imports: [CommonModule, RouterModule] // ✅ Add required Angular modules
})
export class ResourceListComponent implements OnInit {
  resources: Resource[] = [];

  constructor(
    private resourceService: ResourceService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.loadResources();
  }

  loadResources(): void {
    this.resourceService.getResources().subscribe({
      next: (data) => this.resources = data,
      error: (err) => console.error('Error loading resources:', err)
    });
  }

  deleteResource(id: number): void {
    if (confirm('Are you sure you want to delete this resource?')) {
      this.resourceService.deleteResource(id).subscribe({
        next: () => this.loadResources(),
        error: (err) => console.error('Error deleting resource:', err)
      });
    }
  }

  goToEdit(id: number): void {
    this.router.navigate(['/resources/edit', id]);
  }
}

<div class="container mt-4">
  <h2 class="mb-3">Faith-Based Resources</h2>

  <table class="table table-bordered table-hover">
    <thead class="thead-light">
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Category ID</th>
        <th>Scripture</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let resource of resources">
        <td>{{ resource.title }}</td>
        <td>{{ resource.description }}</td>
        <td>{{ resource.category_id }}</td>
        <td>{{ resource.scripture }}</td>
        <td>
          <button
            *ngIf="resource.id !== undefined"
            class="btn btn-sm btn-primary mr-2"
            (click)="goToEdit(resource.id)"
          >
            Edit
          </button>

          <button
            *ngIf="resource.id !== undefined"
            class="btn btn-sm btn-danger"
            (click)="deleteResource(resource.id)"
          >
            Delete
          </button>
        </td>
      </tr>
    </tbody>
  </table>

  <div class="mt-3">
    <a class="btn btn-success" routerLink="/resources/create">Add New Resource</a>
  </div>
</div>

// FaithTrack/frontend-react/src/components/ResourceList.jsx
import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import resourceService from '../services/resourceService.jsx';


function ResourceList() {
  const [resources, setResources] = useState([]);

  const loadResources = async () => {
    try {
      const data = await resourceService.getResources();
      setResources(data);
    } catch (err) {
      console.error('Error loading resources:', err);
    }
  };

  const handleDelete = async (id) => {
    if (window.confirm('Are you sure you want to delete this resource?')) {
      try {
        await resourceService.deleteResource(id);
        loadResources(); // refresh the list
      } catch (err) {
        console.error('Delete failed:', err);
      }
    }
  };

  useEffect(() => {
    loadResources();
  }, []);

  return (
    <div>
      <h2>All Resources</h2>
      {resources.length === 0 ? (
        <p>No resources found.</p>
      ) : (
        <table className="table table-bordered mt-3">
          <thead className="table-dark">
            <tr>
              <th>Title</th>
              <th>Description</th>
              <th>Category ID</th>
              <th>Scripture</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {resources.map((res) => (
              <tr key={res.id}>
                <td>{res.title}</td>
                <td>{res.description}</td>
                <td>{res.category_id}</td>
                <td>{res.scripture}</td>
                <td>
                  <Link
                    to={`/resources/edit/${res.id}`}
                    className="btn btn-sm btn-warning me-2"
                  >
                    Edit
                  </Link>
                  <button
                    className="btn btn-sm btn-danger"
                    onClick={() => handleDelete(res.id)}
                  >
                    Delete
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
}

export default ResourceList;
